"""empty message

Revision ID: 642afa67e249
Revises: ee3128f6da0a
Create Date: 2020-11-26 21:37:30.819360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642afa67e249'
down_revision = 'ee3128f6da0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
