"""empty message

Revision ID: 7019bb1b9ed8
Revises: 642afa67e249
Create Date: 2020-12-04 14:16:19.233737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7019bb1b9ed8'
down_revision = '642afa67e249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('cart', sa.String(), nullable=False))
    op.alter_column('orders', 'datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('orders', 'cart')
    # ### end Alembic commands ###
